podSecurityContext:
  fsGroup: 65534

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

priorityClassName: "infra"

interval: 1m
triggerLoopOnEvent: true

sources:
  - service
  - ingress

policy: sync

registry: txt
txtOwnerId: "banana"

provider: hetzner

env:
- name: HETZNER_TOKEN
  value: "token_here"

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi
