ingress-nginx:
  controller:
    name: private-controller
    containerName: private-controller
    extraArgs:
      enable-ssl-passthrough: ""

    ingressClassResource:
      name: private
      enabled: true
      default: true
      controllerValue: "k8s.io/ingress-nginx"
    ingressClass: private

    kind: DaemonSet
    minReadySeconds: 5

    resources:
      limits:
        cpu: 1.5
        memory: 1.5Gi
      requests:
        cpu: 100m
        memory: 90Mi

    service:
      type: ClusterIP # tailscale proxy in front
      clusterIP: 10.111.0.100 # needs to be static tailscale proxy
      externalTrafficPolicy: "" # needs to be empty for tailscale proxy

    priorityClassName: "infra"

    image:
      allowPrivilegeEscalation: false
    containerSecurityContext:
      runAsUser: 101
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  defaultBackend:
    enabled: true
    replicaCount: 1
    minAvailable: 0
    runAsUser: 65534
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi
  dhParam: LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBaHNtRjdjMkppaHd4Zll4R3R1a1cweml1NlcvNndiaXQ4U1NXcXJ2cndDb0Y0WHRwYzQrZgpidEd0ZDZkb1dpdE9nUnFLNkVXcDdwZFMyb085OUN6Q2JHdnFBTktWR1pYSzVlTnM3K1l1K2lnaHBvT1hHZldvCjlhVGFkVjFWSE9zWEdNT3VBU0kzRXJYcW9OYUtTWkRwZUo1Tk9FK0NUa0RDVmJmQWNEZTV4dTlWbUJZZWZTcisKYjdwL0cwQ21aZFRWWmg4S29jRGJxSHJFaHVKYThHTUYwbFVnU1RkaVhUMklzTk1JNE93bzBkUmtvTXNuQitOTgpQVjFxUS9LbGlOSUR5eFNYcEw4eDRDQTZMR2xKSzd3cDd0NnFBb1NleXVBTWlIdFNCMHFZNEZQTFRIYTdqRFZnCkxiR2w2bTU3U2xpT1hJUXdpMGZnUDZjQWpZQ3l5YnJZUGdhWTl3TzVSRHM5ZzhMM0dNMkZjS0R4OHBYb3dmakwKOElJYk41SmFKdnFoSEpGKzNObW5CNnh5ZTVNV01QOVJmckU4UFpJVklQZWc5a0p2Z0hiYU5tR0JGSCtacjdSRAp3SGhEK1p6bENYYisxK2tKNSt4UFVqZHBucmllODN3RWV0RUV6OXNqRHc4L3BrVk5MNFpmM21qcXlKQjA0L0RYCkxzUFJaZWN6NWtoRmFlRWhKMzVuclJVdmp1ZjRrQUg3MUNPa0pMeUR6c1ZzY3dZSFpTalpuQWwzU0tkdkNwa3EKMWNHOWpxZVEzcHAwekdBOXRhYXVTaTQrM3U0ZVgyWGpHS3BRVjVUUjBILzZpVEdTd3lQV1REN1dNYTYvVm9rbgpPeWJPd1p2NmlGeFFTbzBOVDZCWXpEckJlYWgwajNoanN0WVdpd1dMN21CTWRXSjEwU3RnMDFjQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg==
