apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tailscale
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/part-of: tailscale
  ingress:
    # Entire telnet should be able to reach the proxy
    - fromEntities:
        - world
  egress:
    - toEntities:
    # Allow proxy to talk to tailscale service (currently no idea what type of connections)
        - world
    # Allow connections to the kubeapi
        - "kube-apiserver"
    # Allow proxy to forward requests to contour-private
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: contour
            app.kubernetes.io/instance: contour-private
            io.kubernetes.pod.namespace: contour-private
      # toPorts:
      #   - ports:
      #       - port: "443"
      #   - ports:
      #       - port: "80"
