apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: addons
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.6.x
    helm:
      version: v3
      values: |-
        fullnameOverride: "sealed-secrets-controller"
        keyrenewperiod: "720h30m"
        priorityClassName: "system-cluster-critical"
        resources:
          limits: 
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 5m
            memory: 10Mi
        podSecurityContext:
          enabled: true
          fsGroup: 65534
        containerSecurityContext:
          enabled: true
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        networkPolicy:
          enabled: true
